[project]
name = "dotslash-python"
version = "0.1.0"
description = "A single-file CPython distribution you can check into a repository"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pyrefly>=0.14.0",
]
